"""Walk-forward orchestration.

For each rolling window we pick the best factor parameters on the in-sample
(train) slice, then evaluate those params on the out-of-sample (test) slice, and
stitch the test slices into one continuous OOS return series. That stitched curve
is the honest estimate of live performance: every point was generated by params
chosen *without* seeing it.

With no parameter grid the selection is trivial (one candidate), so this reduces
to a rolling fixed-parameter OOS evaluation, still useful for robustness.

Efficiency: a candidate's full-period returns do not depend on the window, so we
compute each candidate's full backtest ONCE, then slice per window. Cost is
O(grid) engine runs, not O(grid x windows).
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass

import pandas as pd

from alphaforge.config import BacktestConfig
from alphaforge.metrics.performance import compute_metrics, sharpe
from alphaforge.runner import Inputs, compute_result, load_inputs
from alphaforge.validation.walkforward import WalkForwardWindow, generate_windows


@dataclass
class WindowResult:
    window: WalkForwardWindow
    params: dict          # factor params chosen on this window's train slice
    train_sharpe: float   # in-sample Sharpe of the chosen params
    test_sharpe: float    # out-of-sample Sharpe achieved
    test_return: float    # out-of-sample total return


@dataclass
class WalkForwardResult:
    oos_returns: pd.Series          # stitched out-of-sample daily returns
    oos_equity: pd.Series           # OOS equity curve
    windows: list[WindowResult]
    config: BacktestConfig
    benchmark_sharpe: float         # fixed base-params Sharpe over the same OOS span

    def metrics(self):
        return compute_metrics(self.oos_returns)


def param_grid(grid: dict | None) -> list[dict]:
    """Cartesian product of {param: [values]} into a list of param dicts.
    Empty/None grid yields a single empty override (use the config params)."""
    if not grid:
        return [{}]
    keys = list(grid)
    return [dict(zip(keys, combo)) for combo in itertools.product(*(grid[k] for k in keys))]


def _with_factor_params(cfg: BacktestConfig, params: dict) -> BacktestConfig:
    merged = {**cfg.factor.params, **params}
    return cfg.model_copy(update={"factor": cfg.factor.model_copy(update={"params": merged})})


def walk_forward_from_returns(
    candidates: list[tuple[dict, pd.Series]],
    windows: list[WalkForwardWindow],
    cfg: BacktestConfig,
    benchmark_returns: pd.Series,
) -> WalkForwardResult:
    """Pure core: given each candidate's (params, full_returns) and the windows,
    select on train and stitch the OOS test slices. No I/O, so it is unit-tested
    directly."""
    segments: list[pd.Series] = []
    window_results: list[WindowResult] = []

    for w in windows:
        train = slice(str(w.train_start), str(w.train_end))
        test = slice(str(w.test_start), str(w.test_end))

        best_params, best_returns, best_train_sharpe = None, None, float("-inf")
        for params, returns in candidates:
            s = sharpe(returns.loc[train])
            if s > best_train_sharpe:
                best_params, best_returns, best_train_sharpe = params, returns, s

        test_slice = best_returns.loc[test]
        segments.append(test_slice)
        window_results.append(
            WindowResult(
                window=w,
                params=best_params,
                train_sharpe=best_train_sharpe,
                test_sharpe=sharpe(test_slice),
                test_return=float((1 + test_slice).prod() - 1),
            )
        )

    oos = pd.concat(segments).sort_index()
    oos = oos[~oos.index.duplicated(keep="first")]
    oos_equity = cfg.initial_cash * (1 + oos).cumprod()
    bench_sharpe = sharpe(benchmark_returns.reindex(oos.index).fillna(0.0)) if len(oos) else 0.0

    return WalkForwardResult(
        oos_returns=oos,
        oos_equity=oos_equity,
        windows=window_results,
        config=cfg,
        benchmark_sharpe=bench_sharpe,
    )


def walk_forward(
    cfg: BacktestConfig,
    train_months: int = 36,
    test_months: int = 12,
    step_months: int | None = None,
    anchored: bool = False,
    grid: dict | None = None,
    inputs: Inputs | None = None,
) -> WalkForwardResult:
    """Run a walk-forward study. Loads data once, computes each grid candidate's
    full backtest once, then rolls the windows."""
    inputs = inputs or load_inputs(cfg)
    full_index = inputs.prices["close"].index

    candidates: list[tuple[dict, pd.Series]] = []
    for params in param_grid(grid):
        result = compute_result(inputs, _with_factor_params(cfg, params))
        candidates.append((params, result.returns.reindex(full_index).fillna(0.0)))

    # The benchmark is the fixed base-params strategy (no optimization).
    benchmark = compute_result(inputs, cfg).returns.reindex(full_index).fillna(0.0)

    windows = generate_windows(
        cfg.data.start, cfg.data.end, train_months, test_months, step_months, anchored
    )
    if not windows:
        raise ValueError(
            "No walk-forward windows fit the date range; shorten train/test months "
            "or widen the backtest period."
        )

    return walk_forward_from_returns(candidates, windows, cfg, benchmark)
